version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: cms-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cms
      POSTGRES_USER: cms_user
      POSTGRES_PASSWORD: cms_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
